# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hme < Formula
  desc "iCloud Hide My Email CLI — generate aliases from the command line"
  homepage "https://github.com/mark-liu/hme"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-liu/hme/releases/download/v0.1.1/hme_darwin_amd64.tar.gz"
      sha256 "079b3d110d07b55b12f2ccd2f97a37e37035c63f6aea85a85ab87b012a19f3d3"

      define_method(:install) do
        bin.install "hme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-liu/hme/releases/download/v0.1.1/hme_darwin_arm64.tar.gz"
      sha256 "c95837335dae4acff4bf1316ba6362fb26d8231812a202a14cf357c9ae474385"

      define_method(:install) do
        bin.install "hme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/hme/releases/download/v0.1.1/hme_linux_amd64.tar.gz"
      sha256 "220b6626b009446d77297fca6446d3c11206765677f1102d1ea8e9fffeed271e"
      define_method(:install) do
        bin.install "hme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/hme/releases/download/v0.1.1/hme_linux_arm64.tar.gz"
      sha256 "20e1c586f8d7a84f219dfb539833cf9b446d8f34871be02f267c1d53c8bca88b"
      define_method(:install) do
        bin.install "hme"
      end
    end
  end

  test do
    assert_match "hme", shell_output("#{bin}/hme --version")
  end
end
