# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpguard < Formula
  desc "MCP stdio proxy — prompt injection scanning and payload compression for LLM safety"
  homepage "https://github.com/mark-liu/mcpguard"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-liu/mcpguard/releases/download/v0.1.1/mcpguard_0.1.1_darwin_amd64.tar.gz"
      sha256 "f7c88fd586c5ad8810c92b6a587514b97695b348d7b0a4cf9c8acc43d23a8eb9"

      define_method(:install) do
        bin.install "mcpguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-liu/mcpguard/releases/download/v0.1.1/mcpguard_0.1.1_darwin_arm64.tar.gz"
      sha256 "43af2c339b2564ae51b6dda286623d5929639b8511fca53cceb327ca235dd9b4"

      define_method(:install) do
        bin.install "mcpguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/mcpguard/releases/download/v0.1.1/mcpguard_0.1.1_linux_amd64.tar.gz"
      sha256 "3b7dbf9a88579a56db9a9589c20a6542653a837d539364036eef47ceabfa37c0"
      define_method(:install) do
        bin.install "mcpguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/mcpguard/releases/download/v0.1.1/mcpguard_0.1.1_linux_arm64.tar.gz"
      sha256 "c96de887f95b24ec502f4c4e4b49e4e1defca4206201d7d510bd3e5d9167cfb1"
      define_method(:install) do
        bin.install "mcpguard"
      end
    end
  end

  test do
    assert_match "mcpguard", shell_output("#{bin}/mcpguard --help 2>&1", 1)
  end
end
