# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebguardMcp < Formula
  desc "Secure web fetching MCP server for LLM agents — local prompt injection scanning"
  homepage "https://github.com/mark-liu/webguard-mcp"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.3.0/webguard-mcp_0.3.0_darwin_amd64.tar.gz"
      sha256 "1262b4bf1ec7a58873cc884e42f56b1f3ec2da5ff4471bce662379f3c6d6c062"

      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.3.0/webguard-mcp_0.3.0_darwin_arm64.tar.gz"
      sha256 "e8b23e7365f16f010d5dc0077c5d394ff0fe45a7188e230bed5560fc090234be"

      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.3.0/webguard-mcp_0.3.0_linux_amd64.tar.gz"
      sha256 "173d5c8f0e20636a90bca2b24b826aa231bb38cda8ee8e509291d6217d2bf501"
      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.3.0/webguard-mcp_0.3.0_linux_arm64.tar.gz"
      sha256 "c5cb12fce7f35add5d38343bba5ba9445218c6c185a30c0a496513fe366cf13f"
      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
  end

  test do
    assert_match "webguard-mcp", shell_output("#{bin}/webguard-mcp --version")
  end
end
