# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebguardMcp < Formula
  desc "Secure web fetching MCP server for LLM agents — local prompt injection scanning"
  homepage "https://github.com/mark-liu/webguard-mcp"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.6.0/webguard-mcp_0.6.0_darwin_amd64.tar.gz"
      sha256 "005beebdd06448cc3831425f2802111dcda26fa7b11fccd42619d35761539d50"

      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.6.0/webguard-mcp_0.6.0_darwin_arm64.tar.gz"
      sha256 "76b40294382e6120f37ffb6e605b359e5dc3e08426146b73b404752e5acd78e0"

      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.6.0/webguard-mcp_0.6.0_linux_amd64.tar.gz"
      sha256 "9ed1ed6276a3aedb9485bbb7469aeac9f81e625bc26c82e579ba6e0a0ce3a36a"
      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.6.0/webguard-mcp_0.6.0_linux_arm64.tar.gz"
      sha256 "0b67a627356d6c3f68d5921d6d5fea0141a8dbabe5714e58ac11c0c8b0d78a37"
      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
  end

  test do
    assert_match "webguard-mcp", shell_output("#{bin}/webguard-mcp --version")
  end
end
