# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebguardMcp < Formula
  desc "Secure web fetching MCP server for LLM agents — local prompt injection scanning"
  homepage "https://github.com/mark-liu/webguard-mcp"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.2.0/webguard-mcp_0.2.0_darwin_amd64.tar.gz"
      sha256 "d9f6334e1d9520f17733c7396b57445a16d5a028c8f00922ed34648b2fd82d52"

      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.2.0/webguard-mcp_0.2.0_darwin_arm64.tar.gz"
      sha256 "51deb4811b50bbe112d2285ef235e384e36964720ead3ad96ad2eb60018bc35f"

      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.2.0/webguard-mcp_0.2.0_linux_amd64.tar.gz"
      sha256 "530e09706027999cac1ee84adc169e11c2f2fa605c9d8cd2c5c006ef975a702e"
      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-liu/webguard-mcp/releases/download/v0.2.0/webguard-mcp_0.2.0_linux_arm64.tar.gz"
      sha256 "f51c490cbf9be8984ca9dfc0019212aabecea39d29fa762af3ef1df6cf89bed9"
      define_method(:install) do
        bin.install "webguard-mcp"
      end
    end
  end

  test do
    assert_match "webguard-mcp", shell_output("#{bin}/webguard-mcp --version")
  end
end
